### ISSUE TITLE
[feat] Change to a mobile-friendly calendar library

### ISSUE THREAD

**Issue by get6** [get6/get912000won#1]
## 📢 Description

캘린더가 PC에서 테스트해봤을 때 잘 선택되었는데 모바일 터치에서는 느린감이 있습니다.
이를 해결한 라이브러리를 찾아 변경하고자 합니다.

## 💎 Requirements

기존 기능을 그대로 이어받기 + (터치 이슈 해결, 스크롤 터치 가능?)

## ✨ Todo

- [ ] 모바일 친화적 캘린더 라이브러리 찾기
- [x] 기존 기능이 다 되는지 확인
- [x] 기존 라이브러리 제거
- [x] 잘 되는지 테스트

**Comment by get6** [comment]
해당 브랜치에서 캘린더 봤을 때 날짜를 선택했을 때 실제 선택되었는지 확인이 어려웠습니다. 이전에는 그림자로 구분을 했던 것 같은데 그림자가 추가되거나 아니면 선택된 색과 비슷한 색으로 달라지는 것도 좋을 것 같습니다.
