### ISSUE TITLE
[feat] Apply prettier to project

### ISSUE THREAD

**Issue by get6** [get6/get912000won#3]
## 📢 Description

협업을 위해 [prettier](https://prettier.io/) 설정을 합니다.
작업자마다 설정이 다르면 고치지 않아도 될 부분이 변경되기 때문에 프로젝트에 프리티어 관련 파일을 만듭니다.

## 💎 Requirements

prettier 파일 만들기
코드라인 마지막에 `;` 붙지 않도록 하기
저장 시  프리티어 포맷으로 저장되도록 하기 (각자 VS Code에 있는 settings.json 파일에다 적용하기)

## ✨ Todo

- [x] prettier가 프로젝트에 설치되어 있지 않다면 설치
- [x] prettier 설정 살펴보기
- [x] prettier 파일 생성
- [x] 저장 시 prettier format으로 저장되게끔 변경
- [x] 예상대로 동작하는지 테스트

## 🐣 ETC

추가적으로 하고싶은 옵션이 있으면 알려주세요~ 적용해봅시다!
