### ISSUE TITLE
[bug] page blink when refreshing in dark theme

### ISSUE THREAD

**Issue by hux2** [get6/get912000won#9]
## 📢 Description

다크모드일 때 새로고침을 하면 화면이 한 번 흰색으로 깜빡이는 문제가 있습니다. 
페이지가 기본적으로 흰 색으로 렌더링되다가 theme 정보를 받아온 이후 다크모드로 렌더링되기 때문인 것 같은데,
문제를 정확히 파악하고 고쳐보도록 합시다.

## 💎 Requirements

다크모드일 때 새로고침을 해도 하얗게 깜빡이지 않도록 구현할 것.

## ✨ Todo

- [ ] 문제의 원인 파악하기
- [ ] 문제 해결하여 코드 수정하기
- [ ] 문제가 해결된 이후 기존과 동일하게 동작하는지 확인하기 

## 🐣 ETC

웹개발 어려워잉

**Comment by hux2** [comment]
flickering을 고치기는 했는데.. 아이콘 렌더링이 생각보다 느리네요. 이거 제대로 고치려면 next-themes 라이브러리를 사용하는 대신 자체적으로 theme mode를 구현해야 완전 깔끔하게 동작할 것 같습니다. 이건 좀 더 공부해서 나~중에 시도해보겠습니다. next-themes 쓰는게 너무 편해서 여기에 시간 쏟는건 오버 엔지니어링이라는 생각입니당 허허
